import 'server-only'

import { runAllChecks } from '@tscircuit/checks'
import { runTscircuitCode } from '@tscircuit/eval'
import { generateText, Output } from 'ai'
import type { AnyCircuitElement } from 'circuit-json'
import { z } from 'zod'

import type {
  DesignDiagnostic,
  DesignResult,
  DesignStats,
} from '@/lib/design'

const MAX_REPAIR_ITERATIONS = 3
const MAX_CODE_LENGTH = 80_000
const MODEL_ID = process.env.GEMINI_MODEL?.trim() || 'google/gemini-2.5-pro'

const designBriefSchema = z.object({
  status: z.enum(['ready', 'needs_clarification']),
  questions: z.array(z.string()).max(5),
  summary: z.string(),
  assumptions: z.array(z.string()).max(20),
  requirements: z.array(z.string()).max(40),
})

type DesignBrief = z.infer<typeof designBriefSchema>

type AgentCallbacks = {
  onStage: (message: string) => void
}

const SYSTEM_PROMPT = `You are a senior PCB design engineer using tscircuit. Convert requirements into a single self-contained tscircuit TSX module that compiles to Circuit JSON.

Engineering rules:
- Return only TSX source, with no markdown fences or explanation.
- Export one default React component. Do not import anything and do not access any external API.
- Use tscircuit intrinsic elements such as board, group, chip, resistor, capacitor, inductor, diode, led, trace, net, pinheader, pushbutton, switch, crystal, mosfet, transistor, and potentiometer.
- Every physical component needs a real footprint, reference name, schematic position, and PCB position.
- Define chip pinLabels and connect traces using stable selectors such as .U1 > .VCC or .R1 > .pin1.
- Include power input, decoupling, ground return, connectors, protection, pull-ups, programming/debug access, and test points when required by the brief.
- Size the board around the circuit, keep connectors at accessible edges, and place decoupling close to IC supply pins.
- Use routed PCB traces generated by tscircuit. Avoid overlapping components and keep copper inside the board.
- Prefer standard, readily available SMD footprints and include manufacturerPartNumber or supplierPartNumbers when confidently known.
- Never invent a connection silently. Use the supplied assumptions and requirements.
- Do not use JavaScript APIs, dynamic property access, loops without fixed bounds, timers, fetch, eval, Function, process, globalThis, window, document, WebSocket, or dynamic imports.`

export async function analyzeDesignRequest(
  messages: string[],
): Promise<DesignBrief> {
  const { output } = await generateText({
    model: MODEL_ID,
    output: Output.object({ schema: designBriefSchema }),
    abortSignal: AbortSignal.timeout(45_000),
    prompt: `Review this PCB design conversation and decide whether the electrical and mechanical requirements are sufficient to generate a real design.

Ask only critical questions that materially change safety or function: supply voltage/range, maximum current, required interfaces, board dimensions/connector constraints, load characteristics, or exact controller when relevant. Do not ask cosmetic questions. If earlier messages answer a question, do not ask it again.

Conversation:
${messages.map((message, index) => `${index + 1}. ${message}`).join('\n')}`,
  })

  if (!output) throw new Error('Gemini did not return a design brief.')
  return output
}

function extractTsx(text: string) {
  const fenced = text.match(/```(?:tsx|typescript|jsx|ts)?\s*([\s\S]*?)```/i)
  const code = (fenced?.[1] ?? text).trim()
  if (!code) throw new Error('Gemini returned empty circuit source.')
  if (code.length > MAX_CODE_LENGTH) throw new Error('Generated circuit source is too large.')
  return code
}

function assertSafeGeneratedCode(code: string) {
  const forbidden = [
    /\bimport\s*(?:\(|[^.])/,
    /\brequire\s*\(/,
    /\b(?:process|globalThis|window|document|Deno|Bun)\b/,
    /\b(?:eval|Function|fetch|XMLHttpRequest|WebSocket|Worker)\s*\(/,
    /\b(?:child_process|node:|fs\/promises|filesystem)\b/,
    /__proto__|\.constructor\b/,
  ]

  if (forbidden.some((pattern) => pattern.test(code))) {
    throw new Error('Generated source contained a disallowed runtime capability.')
  }
  if (!/export\s+default/.test(code)) {
    throw new Error('Generated source must export a default circuit component.')
  }
}

function diagnosticFromUnknown(value: unknown): DesignDiagnostic {
  const item = value as Record<string, unknown>
  const type = String(item.type ?? item.error_type ?? 'design_check')
  const isError = type.includes('error')
  return {
    severity: isError ? 'error' : 'warning',
    type,
    message: String(item.message ?? item.error_message ?? type.replaceAll('_', ' ')),
  }
}

function dedupeDiagnostics(diagnostics: DesignDiagnostic[]) {
  const seen = new Set<string>()
  return diagnostics.filter((diagnostic) => {
    const key = `${diagnostic.type}:${diagnostic.message}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}

function computeStats(circuitJson: AnyCircuitElement[]): DesignStats {
  const board = circuitJson.find((item) => item.type === 'pcb_board') as
    | Record<string, unknown>
    | undefined
  const width = typeof board?.width === 'number' ? board.width : null
  const height = typeof board?.height === 'number' ? board.height : null
  const layers = new Set(
    circuitJson
      .filter((item) => item.type === 'pcb_trace')
      .flatMap((item) => {
        const route = (item as Record<string, unknown>).route
        return Array.isArray(route)
          ? route.map((point) => String((point as Record<string, unknown>).layer ?? 'top'))
          : []
      }),
  )

  return {
    components: circuitJson.filter((item) => item.type === 'source_component').length,
    sourceTraces: circuitJson.filter((item) => item.type === 'source_trace').length,
    routedTraces: circuitJson.filter((item) => item.type === 'pcb_trace').length,
    pcbLayers: Math.max(layers.size, 1),
    boardWidthMm: width,
    boardHeightMm: height,
  }
}

export async function compileAndVerify(code: string) {
  assertSafeGeneratedCode(code)
  const circuitJson = (await runTscircuitCode(code)) as AnyCircuitElement[]
  const emittedDiagnostics = circuitJson
    .filter((item) => item.type.includes('error') || item.type.includes('warning'))
    .map(diagnosticFromUnknown)
  const checks = await runAllChecks(circuitJson)
  const diagnostics = dedupeDiagnostics([
    ...emittedDiagnostics,
    ...checks.map(diagnosticFromUnknown),
  ])

  return {
    circuitJson,
    diagnostics,
    stats: computeStats(circuitJson),
    verified: !diagnostics.some((item) => item.severity === 'error'),
  }
}

async function generateInitialCode(brief: DesignBrief) {
  const { text } = await generateText({
    model: MODEL_ID,
    system: SYSTEM_PROMPT,
    abortSignal: AbortSignal.timeout(90_000),
    prompt: `Create the complete PCB design now.

Summary: ${brief.summary}
Requirements:
${brief.requirements.map((item) => `- ${item}`).join('\n')}
Assumptions:
${brief.assumptions.map((item) => `- ${item}`).join('\n')}`,
  })
  return extractTsx(text)
}

async function repairCode(
  code: string,
  diagnostics: DesignDiagnostic[],
  compileFailure?: string,
) {
  const { text } = await generateText({
    model: MODEL_ID,
    system: SYSTEM_PROMPT,
    abortSignal: AbortSignal.timeout(90_000),
    prompt: `Repair this tscircuit design. Preserve its intended function, but fix every compiler, connectivity, placement, and routing failure. Return the full corrected TSX module only.

Compiler failure: ${compileFailure ?? 'none'}
Diagnostics:
${diagnostics.map((item) => `- [${item.severity}] ${item.type}: ${item.message}`).join('\n') || '- none'}

Current source:
${code}`,
  })
  return extractTsx(text)
}

export async function createVerifiedDesign(
  brief: DesignBrief,
  callbacks: AgentCallbacks,
): Promise<DesignResult> {
  callbacks.onStage(`Generating tscircuit TSX with ${MODEL_ID}`)
  let code = await generateInitialCode(brief)
  let latestDiagnostics: DesignDiagnostic[] = []

  for (let iteration = 1; iteration <= MAX_REPAIR_ITERATIONS + 1; iteration += 1) {
    callbacks.onStage(`Compiling and running ERC/DRC — pass ${iteration}`)
    try {
      const result = await compileAndVerify(code)
      latestDiagnostics = result.diagnostics
      if (result.verified) {
        callbacks.onStage('Verification passed; manufacturing exports unlocked')
        return {
          tsx: code,
          circuitJson: result.circuitJson,
          summary: brief.summary,
          assumptions: brief.assumptions,
          diagnostics: result.diagnostics,
          stats: result.stats,
          verified: true,
          iterations: iteration,
          model: MODEL_ID,
        }
      }

      if (iteration > MAX_REPAIR_ITERATIONS) {
        return {
          tsx: code,
          circuitJson: result.circuitJson,
          summary: brief.summary,
          assumptions: brief.assumptions,
          diagnostics: result.diagnostics,
          stats: result.stats,
          verified: false,
          iterations: iteration,
          model: MODEL_ID,
        }
      }

      callbacks.onStage(
        `Repairing ${result.diagnostics.filter((item) => item.severity === 'error').length} blocking issue(s) with Gemini`,
      )
      code = await repairCode(code, result.diagnostics)
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown compiler failure'
      latestDiagnostics = [{ severity: 'error', type: 'compile_error', message }]
      if (iteration > MAX_REPAIR_ITERATIONS) throw new Error(message)
      callbacks.onStage(`Compiler rejected pass ${iteration}; requesting a repair`)
      code = await repairCode(code, latestDiagnostics, message)
    }
  }

  throw new Error('The autonomous verification loop ended unexpectedly.')
}

export function getConfiguredModel() {
  return MODEL_ID
}
